export default {
  'entry.title': 'Mood Journal', 'entry.mood': 'How do you feel?', 'entry.activities': 'Tags', 'entry.addActivity': 'Add tag', 'entry.journal': 'Journal', 'entry.memo': 'Add a note if you want…', 'entry.changeDate': 'Change date and time', 'entry.closeDate': 'Hide date and time', 'entry.autoDate': 'Use current time', 'entry.date': 'Date', 'entry.time': 'Time', 'entry.cancel': 'Cancel', 'entry.save': 'Save', 'entry.saving': 'Saving…', 'entry.retry': 'Retry', 'entry.copyMarkdown': 'Copy Markdown', 'entry.searchTags': 'Search tags', 'entry.expandTag': 'Show child tags', 'entry.collapseTag': 'Hide child tags',
  'notice.saved': 'Journal entry saved.', 'notice.copied': 'Markdown copied.', 'notice.commandNameReload': 'Display language changed. Reload the plugin to update the command palette name.',
  'error.moodRequired': 'Choose a mood before saving.', 'error.save': 'Could not save the entry. Your input is still here.', 'error.formatRequired': 'Enter a date format.', 'error.templateMissing': 'The specified template was not found.',
  'setup.title': 'Welcome to Mood Journal', 'setup.language': 'Display language', 'setup.daily': 'Daily note settings', 'setup.finish': 'Finish setup', 'setup.next': 'Next', 'setup.back': 'Back', 'setup.manual': 'Configure manually', 'setup.follow': 'Follow Obsidian Daily notes', 'setup.checking': 'Checking Daily notes settings…', 'setup.detected': 'Daily notes settings found', 'setup.folder': 'Folder (empty for vault root)', 'setup.format': 'Date format', 'setup.template': 'Template path (optional)', 'setup.preview': 'Today\'s path', 'setup.initialTags': 'Initial tags', 'setup.saveExample': 'Saved Markdown example', 'setup.vaultRoot': 'Vault root',
  'discard.title': 'Discard this entry?', 'discard.body': 'Unsaved input will be lost.', 'discard.continue': 'Keep editing', 'discard.confirm': 'Discard',
  'tagEditor.title': 'Add tag', 'tagEditor.parent': 'Parent tag', 'tagEditor.newParent': 'New parent tag', 'tagEditor.parentName': 'Parent tag name', 'tagEditor.childOptional': 'Child tag (optional)', 'tagEditor.child': 'Child tag', 'tagEditor.example': 'Example: Walk', 'tagEditor.add': 'Add', 'tagEditor.error': 'Could not add the tag.',
  'settings.title': 'Mood Journal settings', 'settings.language': 'Language', 'settings.daily': 'Daily notes', 'settings.folder': 'Folder', 'settings.format': 'Date format', 'settings.template': 'Template path', 'settings.dailyHelp': 'Choose where journal entries are saved.', 'settings.destination': 'Destination', 'settings.destinationHelp': 'Follow Obsidian settings or configure this plugin manually.', 'settings.moodLabels': 'Mood labels', 'settings.moodLabelsHelp': 'Give each mood label a name you prefer.', 'settings.resetMoodLabels': 'Restore language defaults', 'settings.resetMoodLabelsConfirm': 'Restore all mood labels to the language defaults?', 'settings.reset': 'Restore', 'settings.tags': 'Tags', 'settings.tagsHelp': 'Manage tags for journal entries. Parent and child tags are supported.', 'settings.addTag': 'Add tag', 'settings.searchTags': 'Search tags', 'settings.setup': 'Setup', 'settings.setupHelp': 'Run first-time setup again. Existing tags are unchanged.', 'settings.restartSetup': 'Run first-time setup again', 'settings.start': 'Start', 'settings.visible': 'Visible', 'settings.hidden': 'Hidden', 'settings.restore': 'Restore', 'settings.hide': 'Hide', 'settings.tagRenameError': 'Could not rename the tag.', 'settings.invalidValue': 'Enter a valid value.', 'settings.coreCurrent': 'Current Daily notes settings', 'settings.redetect': 'Detect again', 'settings.coreError': 'Could not read Obsidian Daily notes settings.',
} as const;
