export default {
  'entry.title': '気分を記録', 'entry.mood': '今の気分は？', 'entry.activities': 'タグ', 'entry.addActivity': 'タグを追加', 'entry.journal': '日記', 'entry.memo': '必要なら、今のことを少し書く…', 'entry.changeDate': '日時を変更', 'entry.closeDate': '日時変更を閉じる', 'entry.autoDate': '現在日時を使う', 'entry.date': '日付', 'entry.time': '時刻', 'entry.cancel': 'キャンセル', 'entry.save': '保存', 'entry.saving': '保存中…', 'entry.retry': '再試行', 'entry.copyMarkdown': 'Markdownをコピー', 'entry.searchTags': 'タグを検索', 'entry.expandTag': '子タグを表示', 'entry.collapseTag': '子タグを隠す',
  'notice.saved': '日記を保存しました。', 'notice.copied': 'Markdownをコピーしました。', 'notice.commandNameReload': '表示言語を変更しました。コマンドパレットの名称はプラグインを再読み込みすると反映されます。',
  'error.moodRequired': '気分を選択してください。', 'error.save': '保存できませんでした。入力内容は保持されています。', 'error.formatRequired': '日付形式を入力してください。', 'error.templateMissing': '指定したテンプレートが見つかりません。',
  'setup.title': 'Mood Journal へようこそ', 'setup.language': '表示言語', 'setup.daily': 'デイリーノート設定', 'setup.finish': 'セットアップを完了', 'setup.next': '次へ', 'setup.back': '戻る', 'setup.manual': '手動で設定する', 'setup.follow': 'ObsidianのDaily notes設定に追従', 'setup.checking': 'Daily notes設定を確認中…', 'setup.detected': 'デイリーノート設定が見つかりました', 'setup.folder': '保存先フォルダ（空欄でVaultルート）', 'setup.format': '日付形式', 'setup.template': 'テンプレートパス（任意）', 'setup.preview': '今日の生成予定パス', 'setup.initialTags': '初期タグ', 'setup.saveExample': 'Markdown保存例', 'setup.vaultRoot': 'Vaultルート',
  'discard.title': '入力内容を破棄しますか？', 'discard.body': '保存していない入力内容は失われます。', 'discard.continue': '続ける', 'discard.confirm': '破棄',
  'tagEditor.title': 'タグを追加', 'tagEditor.parent': '親タグ', 'tagEditor.newParent': '新しい親タグ', 'tagEditor.parentName': '親タグ名', 'tagEditor.childOptional': '子タグ（任意）', 'tagEditor.child': '子タグ', 'tagEditor.example': '例: 散歩', 'tagEditor.add': '追加', 'tagEditor.error': 'タグを追加できませんでした。',
  'settings.title': 'Mood Journal 設定', 'settings.language': '言語', 'settings.daily': 'デイリーノート', 'settings.folder': 'フォルダ', 'settings.format': '日付形式', 'settings.template': 'テンプレートパス', 'settings.dailyHelp': '日記を書く場所を設定できます。', 'settings.destination': '保存先', 'settings.destinationHelp': 'Obsidianの設定に追従するか、このプラグインで指定します。', 'settings.moodLabels': '気分ラベル', 'settings.moodLabelsHelp': '各ラベルごとに好きな名前を付けられます。', 'settings.resetMoodLabels': '言語の初期値へ戻す', 'settings.resetMoodLabelsConfirm': 'すべての気分ラベルを言語の初期値に戻しますか？', 'settings.reset': '戻す', 'settings.tags': 'タグ', 'settings.tagsHelp': '日記に付けたいタグを管理しましょう。親タグとそれに紐づく子タグが設定できます。', 'settings.addTag': 'タグを追加', 'settings.searchTags': 'タグを検索', 'settings.setup': 'セットアップ', 'settings.setupHelp': '初回セットアップをやり直します。既存のタグは変更されません。', 'settings.restartSetup': '初回セットアップをやり直す', 'settings.start': '開始', 'settings.visible': '表示中', 'settings.hidden': '非表示', 'settings.restore': '復元', 'settings.hide': '非表示', 'settings.tagRenameError': 'タグ名を変更できませんでした。', 'settings.invalidValue': '有効な値を入力してください。', 'settings.coreCurrent': '現在のDaily notes設定', 'settings.redetect': '再検出', 'settings.coreError': 'ObsidianのDaily notes設定を読み取れませんでした。',
} as const;
